[package]
name = "comp_graph"
version = "0.1.0"
authors = ["MonadicDavidHuang <mynameistoyoko@gmail.com>"]

[dependencies]
ndarray = "0.11.0"
ndarray-linalg = { version = "0.9.0", features = ["openblas"] }
