[package]
name = "computation-graph"
version = "0.1.0"
authors = ["MonadicDavidHuang <mynameistoyoko@gmail.com>"]
edition = "2018"

[dependencies]
either = "1.5"
rand = "0.4"
ndarray = "0.13"
ndarray-rand = "0.7.0"
ndarray-linalg = { version = "0.12", features = ["openblas"] }