[package]
name = "computation_graph"
version = "0.1.0"
authors = ["MonadicDavidHuang <mynameistoyoko@gmail.com>"]

[dependencies]
rand = "0.4"
ndarray = "0.12.0"
ndarray-rand = "0.7.0"
ndarray-linalg = "0.10"
# openblas-src = "0.5" # or another backend of your choice
